theme: jekyll-theme-architect
title: RJB Solutions
description: Blogging Power Platform and Dev Stuff
show_downloads: true
#google_analytics: [Your Google Analytics tracking ID]

excerpt_separator: <!--more-->

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/2021-11-10"
    values:
      image: true
